/* The iframe uses src (not data-src): it loads once and retains its state. */
const deck = new Reveal({width:1280,height:720,margin:0.025,minScale:0.1,maxScale:3,hash:true,history:true,controls:false,progress:true,center:false,transition:'none',backgroundTransition:'none',overview:true,keyboard:true,slideNumber:false,disableLayout:false,plugins:[RevealNotes]});
const prev=document.getElementById('previous'),next=document.getElementById('next'),counter=document.getElementById('counter');
function sync(){const index=deck.getIndices().h,total=deck.getTotalSlides();counter.textContent=`${index+1} / ${total}`;prev.disabled=index===0;next.disabled=index===total-1;document.body.classList.toggle('is-demo',deck.getCurrentSlide()?.id==='digital');document.title=`${index+1}. ${deck.getCurrentSlide()?.dataset.title||'CE2134'} · CDE TTG Workshop`;}
prev.addEventListener('click',()=>deck.prev());next.addEventListener('click',()=>deck.next());document.getElementById('overview').addEventListener('click',()=>deck.toggleOverview());document.getElementById('fullscreen').addEventListener('click',()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen());document.getElementById('notes').addEventListener('click',()=>deck.getPlugin('notes').open());
const simulationFrame=document.getElementById('bernoulli');
function syncSimulation(){simulationFrame.contentWindow?.postMessage({type:'ce2134:visibility',active:deck.getCurrentSlide()?.id==='digital'&&!deck.isOverview()},location.origin);}
simulationFrame.addEventListener('load',syncSimulation);
window.addEventListener('message',event=>{if(event.origin!==location.origin||event.source!==simulationFrame.contentWindow)return;if(event.data?.type==='ce2134:ready')syncSimulation();if(event.data?.type==='ce2134:navigate'){const action=event.data.action;if(action==='next')deck.next();if(action==='previous')deck.prev();if(action==='overview')deck.toggleOverview();if(action==='fullscreen')document.getElementById('fullscreen').click();}});
let idle;function showControls(){document.body.classList.remove('controls-idle');clearTimeout(idle);idle=setTimeout(()=>document.body.classList.add('controls-idle'),2800);}document.addEventListener('pointermove',showControls);document.addEventListener('keydown',showControls);deck.on('slidechanged',()=>{sync();syncSimulation();showControls();});deck.on('overviewshown',syncSimulation);deck.on('overviewhidden',syncSimulation);deck.initialize().then(()=>{sync();syncSimulation();showControls();});window.workshopDeck=deck;
